// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/intervals": {
            "post": {
                "description": "Creates an interval with the data provided in the request body",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "intervals"
                ],
                "summary": "Create a new interval",
                "parameters": [
                    {
                        "description": "Interval data",
                        "name": "interval",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.Interval"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Interval successfully created",
                        "schema": {
                            "$ref": "#/definitions/domain.Interval"
                        }
                    },
                    "400": {
                        "description": "Invalid input",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/users": {
            "post": {
                "description": "Creates a user with the data provided in the request body",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Create a new user",
                "parameters": [
                    {
                        "description": "User data",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.User"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "User successfully created",
                        "schema": {
                            "$ref": "#/definitions/domain.User"
                        }
                    },
                    "400": {
                        "description": "Invalid input",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/users/{id}": {
            "get": {
                "description": "Returns the user data for the specified ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Get user by ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "User ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "User found",
                        "schema": {
                            "$ref": "#/definitions/domain.User"
                        }
                    },
                    "400": {
                        "description": "Invalid user ID",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "User not found",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "domain.Activity": {
            "type": "object",
            "properties": {
                "distance": {
                    "description": "Total distance in meters",
                    "type": "number"
                },
                "duration": {
                    "description": "Duration of the activity in string format, e.g., \"1h30m\"",
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "intervals": {
                    "description": "Breakdown of the swim into segments",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/domain.Interval"
                    }
                },
                "laps": {
                    "description": "Number of pool laps",
                    "type": "integer"
                },
                "location_type": {
                    "description": "\"pool\" or \"open_water\"",
                    "allOf": [
                        {
                            "$ref": "#/definitions/domain.LocationType"
                        }
                    ]
                },
                "notes": {
                    "description": "Optional notes",
                    "type": "string"
                },
                "pool_size": {
                    "description": "Pool length in meters (0 if open water)",
                    "type": "number"
                },
                "start": {
                    "description": "Start time of the activity",
                    "type": "string"
                },
                "user_id": {
                    "description": "UserID is the ID of the user who performed the activity",
                    "type": "integer"
                }
            }
        },
        "domain.Interval": {
            "type": "object",
            "properties": {
                "activity_id": {
                    "description": "Foreign key to the swim activity/session",
                    "type": "integer"
                },
                "distance": {
                    "description": "Distance in meters",
                    "type": "number"
                },
                "duration": {
                    "description": "Duration of the interval in string format, e.g., \"1h30m\"",
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "notes": {
                    "description": "Optional notes like \"felt strong\", \"used fins\"",
                    "type": "string"
                },
                "start_time": {
                    "description": "Start time of the interval",
                    "type": "string"
                },
                "stroke": {
                    "description": "Type of swimming stroke",
                    "allOf": [
                        {
                            "$ref": "#/definitions/domain.StrokeType"
                        }
                    ]
                },
                "type": {
                    "description": "One of the predefined types",
                    "allOf": [
                        {
                            "$ref": "#/definitions/domain.IntervalType"
                        }
                    ]
                }
            }
        },
        "domain.IntervalType": {
            "type": "string",
            "enum": [
                "swim",
                "rest",
                "drill",
                "kick",
                "pull",
                "warmup",
                "main_set",
                "cooldown"
            ],
            "x-enum-varnames": [
                "IntervalSwim",
                "IntervalRest",
                "IntervalDrill",
                "IntervalKick",
                "IntervalPull",
                "IntervalWarmUp",
                "IntervalMainSet",
                "IntervalCoolDown"
            ]
        },
        "domain.LocationType": {
            "type": "string",
            "enum": [
                "pool",
                "open_water"
            ],
            "x-enum-varnames": [
                "LocationPool",
                "LocationOpenWater"
            ]
        },
        "domain.StrokeType": {
            "type": "string",
            "enum": [
                "freestyle",
                "backstroke",
                "breaststroke",
                "butterfly",
                "medley",
                "unknown"
            ],
            "x-enum-varnames": [
                "StrokeFreestyle",
                "StrokeBackstroke",
                "StrokeBreaststroke",
                "StrokeButterfly",
                "StrokeMedley",
                "StrokeUnknown"
            ]
        },
        "domain.User": {
            "type": "object",
            "properties": {
                "activities": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/domain.Activity"
                    }
                },
                "city": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "phone": {
                    "type": "string"
                }
            }
        },
        "handler.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "description": "Error is a description of what went wrong.\nExample: Service error",
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Swim Tracker API",
	Description:      "This is an API for tracking swimming",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
